name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: ğŸ”§ **tpl-lexer** test
      run: |
        cargo test --package tpl-lexer --verbose -- --show-output

    - name: âš™ï¸ **tpl-parser** test
      run: |
        cargo test --package tpl-parser --verbose -- --show-output

    # tpl-ir module cannot be tested because of LLVM

  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: âš™ï¸ Check
        run: |
          cargo check --workspace --exclude tpl-ir

      - name: ğŸš€ Clippy
        run: |
          cargo clippy --no-deps --workspace -- -D warnings
